services:
  mysql:
    image: mysql:8.0
    container_name: sync_mysql
    restart: always
    command: --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: syncdb
      MYSQL_USER: syncuser
      MYSQL_PASSWORD: syncpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: sync_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
